apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cass-operator
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - services
      - endpoints
      - persistentvolumeclaims
      - events
      - configmaps
      - secrets
    verbs:
      - '*'
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
  - apiGroups:
      - apps
    resources:
      - deployments
      - daemonsets
      - replicasets
      - statefulsets
    verbs:
      - '*'
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - servicemonitors
    verbs:
      - get
      - create
  - apiGroups:
      - apps
    resourceNames:
      - cass-operator
    resources:
      - deployments/finalizers
    verbs:
      - update
  - apiGroups:
      - datastax.com
    resources:
      - '*'
    verbs:
      - '*'
  - apiGroups:
      - policy
    resources:
      - poddisruptionbudgets
    verbs:
      - '*'
  - apiGroups:
      - cassandra.datastax.com
    resources:
      - '*'
    verbs:
      - '*'
  - apiGroups:
      - batch
    resources:
      - '*'
    verbs:
      - '*'

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cass-operator-clusterrole
rules:
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - validatingwebhookconfigurations
  verbs:
  - create
  - get
  - update
  resourceNames:
  - "cassandradatacenter-webhook-registration"
- apiGroups:
    - cassandra.datastax.com
  resources:
    - CassandraDatacenter
  verbs:
    - '*'

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cass-operator
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cass-operator
subjects:
  - kind: ServiceAccount
    name: cass-operator
    namespace: default
roleRef:
  kind: ClusterRole
  name: cass-operator-cluster-role
  apiGroup: rbac.authorization.k8s.io

  
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cass-operator
subjects:
  - kind: ServiceAccount
    name: cass-operator
roleRef:
  kind: Role
  name: cass-operator
  apiGroup: rbac.authorization.k8s.io
