# Default values for dc.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: datastax/dse-server
  pullPolicy: IfNotPresent
  tag: "6.8.4-ubi7"

configBuilder:
  repository: datastax/cass-config-builder
  tag: "1.0.3"

storage:
  storageClassName: standard
  size: 2Gi